before_script:
  - docker info

build_image:
  script:
    - docker build -t registry.iutbeziers.fr/debianiut:jessie .
    - docker push  registry.iutbeziers.fr/debianiut:jessie 
    - docker build -t registry.iutbeziers.fr/debianiut:stretch -f /opt/dockerfiles/debianiut/Dockerfile.stretch .
    - docker push registry.iutbeziers.fr/debianiut:stretch 
    - docker tag  registry.iutbeziers.fr/debianiut:latest registry.iutbeziers.fr/debianiut:stretch
    - docker push registry.iutbeziers.fr/debianiut:latest
