before_script:
  - docker info

build_image:
  script:
    - docker build -t registry.iutbeziers.fr/debianiut .
    - docker push  registry.iutbeziers.fr/debianiut 
    - docker build -t registry.iutbeziers.fr/debian:stretch -f $(pwd)/Dockerfile.stretch .
    - docker push registry.iutbeziers.fr/debian:stretch 
